import { Patient, Appointment, ClinicalNote, PractitionerDashboardStats } from '../types';

function getRelativeDateISO(offsetDays: number, hour: number = 9, minute: number = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function isSameDay(d1: Date, d2: Date): boolean {
  return (
    d1.getFullYear() === d2.getFullYear() &&
    d1.getMonth() === d2.getMonth() &&
    d1.getDate() === d2.getDate()
  );
}

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'p-1',
    practitioner_id: 'prac-1',
    first_name: 'Elena',
    last_name: 'Rostova',
    email: 'elena@example.com',
    phone: '+1 (555) 9854878',
    date_of_birth: '1990-04-12',
    gender: 'Female',
    status: 'active',
    primary_ailment: 'Generalized Anxiety Disorder',
    notes_summary: 'Ongoing therapy notes for Generalized Anxiety Disorder.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-2',
    practitioner_id: 'prac-1',
    first_name: 'Marcus',
    last_name: 'Vance',
    email: 'marcus@example.com',
    phone: '+1 (555) 6093325',
    date_of_birth: '1985-11-03',
    gender: 'Male',
    status: 'active',
    primary_ailment: 'Major Depressive Disorder',
    notes_summary: 'Ongoing therapy notes for Major Depressive Disorder.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-3',
    practitioner_id: 'prac-1',
    first_name: 'Sophia',
    last_name: 'Chen',
    email: 'sophia@example.com',
    phone: '+1 (555) 6995892',
    date_of_birth: '1998-07-25',
    gender: 'Female',
    status: 'active',
    primary_ailment: 'Social Anxiety',
    notes_summary: 'Ongoing therapy notes for Social Anxiety.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-4',
    practitioner_id: 'prac-1',
    first_name: 'David',
    last_name: 'Miller',
    email: 'david@example.com',
    phone: '+1 (555) 4399800',
    date_of_birth: '1979-02-19',
    gender: 'Male',
    status: 'inactive',
    primary_ailment: 'PTSD',
    notes_summary: 'Ongoing therapy notes for PTSD.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-5',
    practitioner_id: 'prac-1',
    first_name: 'Juan',
    last_name: 'Perez',
    email: 'juan@example.com',
    phone: '+1 (555) 7997416',
    date_of_birth: '1995-04-12',
    gender: 'Male',
    status: 'completed',
    primary_ailment: 'Panic Disorder',
    notes_summary: 'Ongoing therapy notes for Panic Disorder.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-6',
    practitioner_id: 'prac-1',
    first_name: 'Rachel',
    last_name: 'Green',
    email: 'rachel@example.com',
    phone: '+1 (555) 3817910',
    date_of_birth: '1992-09-15',
    gender: 'Female',
    status: 'completed',
    primary_ailment: 'Agoraphobia',
    notes_summary: 'Ongoing therapy notes for Agoraphobia.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-7',
    practitioner_id: 'prac-1',
    first_name: 'Arthur',
    last_name: 'Pendelton',
    email: 'arthur@example.com',
    phone: '+1 (555) 6452125',
    date_of_birth: '1970-12-01',
    gender: 'Male',
    status: 'archived',
    primary_ailment: 'GAD',
    notes_summary: 'Ongoing therapy notes for GAD.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-8',
    practitioner_id: 'prac-1',
    first_name: 'Maria',
    last_name: 'Garcia',
    email: 'maria@example.com',
    phone: '+1 (555) 9454604',
    date_of_birth: '1988-03-22',
    gender: 'Female',
    status: 'active',
    primary_ailment: 'Bipolar II',
    notes_summary: 'Ongoing therapy notes for Bipolar II.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-9',
    practitioner_id: 'prac-1',
    first_name: 'James',
    last_name: 'Smith',
    email: 'james@example.com',
    phone: '+1 (555) 1360224',
    date_of_birth: '1993-01-14',
    gender: 'Male',
    status: 'active',
    primary_ailment: 'Social Anxiety',
    notes_summary: 'Ongoing therapy notes for Social Anxiety.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-10',
    practitioner_id: 'prac-1',
    first_name: 'Linda',
    last_name: 'Johnson',
    email: 'linda@example.com',
    phone: '+1 (555) 1280281',
    date_of_birth: '1982-08-08',
    gender: 'Female',
    status: 'inactive',
    primary_ailment: 'MDD',
    notes_summary: 'Ongoing therapy notes for MDD.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-11',
    practitioner_id: 'prac-1',
    first_name: 'Robert',
    last_name: 'Williams',
    email: 'robert@example.com',
    phone: '+1 (555) 7727677',
    date_of_birth: '1975-05-30',
    gender: 'Male',
    status: 'completed',
    primary_ailment: 'PTSD',
    notes_summary: 'Ongoing therapy notes for PTSD.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-12',
    practitioner_id: 'prac-1',
    first_name: 'Patricia',
    last_name: 'Brown',
    email: 'patricia@example.com',
    phone: '+1 (555) 6200256',
    date_of_birth: '1996-12-11',
    gender: 'Female',
    status: 'active',
    primary_ailment: 'OCD',
    notes_summary: 'Ongoing therapy notes for OCD.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-13',
    practitioner_id: 'prac-1',
    first_name: 'John',
    last_name: 'Jones',
    email: 'john@example.com',
    phone: '+1 (555) 6857685',
    date_of_birth: '1989-10-25',
    gender: 'Male',
    status: 'active',
    primary_ailment: 'Panic Disorder',
    notes_summary: 'Ongoing therapy notes for Panic Disorder.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-14',
    practitioner_id: 'prac-1',
    first_name: 'Jennifer',
    last_name: 'Davis',
    email: 'jennifer@example.com',
    phone: '+1 (555) 8807729',
    date_of_birth: '1991-06-17',
    gender: 'Female',
    status: 'completed',
    primary_ailment: 'GAD',
    notes_summary: 'Ongoing therapy notes for GAD.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-15',
    practitioner_id: 'prac-1',
    first_name: 'Michael',
    last_name: 'Miller',
    email: 'michael@example.com',
    phone: '+1 (555) 4455702',
    date_of_birth: '1999-02-02',
    gender: 'Male',
    status: 'active',
    primary_ailment: 'Adjustment Disorder',
    notes_summary: 'Ongoing therapy notes for Adjustment Disorder.',
    created_at: getRelativeDateISO(-180),
    updated_at: getRelativeDateISO(-2)
  },
  {
    id: 'p-16',
    practitioner_id: 'prac-1',
    first_name: 'Incomplete',
    last_name: 'Patient',
    email: '',
    phone: '',
    date_of_birth: '',
    gender: '',
    status: 'active',
    primary_ailment: 'Anxiety',
    notes_summary: null,
    created_at: getRelativeDateISO(-1),
    updated_at: getRelativeDateISO(-1)
  }
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    patient_name: 'Elena Rostova',
    scheduled_at: getRelativeDateISO(-20, 15, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-elena',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-27, 15, 0)
  },
  {
    id: 'apt-2',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    patient_name: 'Marcus Vance',
    scheduled_at: getRelativeDateISO(-32, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-marcus',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-39, 12, 0)
  },
  {
    id: 'apt-3',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    patient_name: 'Sophia Chen',
    scheduled_at: getRelativeDateISO(-6, 9, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-sophia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-13, 9, 0)
  },
  {
    id: 'apt-4',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    patient_name: 'David Miller',
    scheduled_at: getRelativeDateISO(-12, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-david',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-19, 14, 0)
  },
  {
    id: 'apt-5',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    patient_name: 'Juan Perez',
    scheduled_at: getRelativeDateISO(7, 12, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-juan',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(0, 12, 0)
  },
  {
    id: 'apt-6',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    patient_name: 'Rachel Green',
    scheduled_at: getRelativeDateISO(-4, 15, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-rachel',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-11, 15, 0)
  },
  {
    id: 'apt-7',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    patient_name: 'Arthur Pendelton',
    scheduled_at: getRelativeDateISO(6, 14, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-arthur',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-1, 14, 0)
  },
  {
    id: 'apt-8',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    patient_name: 'Maria Garcia',
    scheduled_at: getRelativeDateISO(-32, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-maria',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-39, 10, 0)
  },
  {
    id: 'apt-9',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    patient_name: 'James Smith',
    scheduled_at: getRelativeDateISO(-1, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-james',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-8, 11, 0)
  },
  {
    id: 'apt-10',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    patient_name: 'Linda Johnson',
    scheduled_at: getRelativeDateISO(-47, 9, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-linda',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-54, 9, 0)
  },
  {
    id: 'apt-11',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    patient_name: 'Robert Williams',
    scheduled_at: getRelativeDateISO(-22, 9, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-robert',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-29, 9, 0)
  },
  {
    id: 'apt-12',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    patient_name: 'Patricia Brown',
    scheduled_at: getRelativeDateISO(-48, 15, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-patricia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-55, 15, 0)
  },
  {
    id: 'apt-13',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    patient_name: 'John Jones',
    scheduled_at: getRelativeDateISO(-26, 10, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-john',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-33, 10, 0)
  },
  {
    id: 'apt-14',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    patient_name: 'Jennifer Davis',
    scheduled_at: getRelativeDateISO(-25, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-jennifer',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-32, 10, 0)
  },
  {
    id: 'apt-15',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    patient_name: 'Michael Miller',
    scheduled_at: getRelativeDateISO(-11, 11, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-michael',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-18, 11, 0)
  },
  {
    id: 'apt-16',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    patient_name: 'Elena Rostova',
    scheduled_at: getRelativeDateISO(-53, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-elena',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-60, 12, 0)
  },
  {
    id: 'apt-17',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    patient_name: 'Marcus Vance',
    scheduled_at: getRelativeDateISO(-21, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-marcus',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-28, 10, 0)
  },
  {
    id: 'apt-18',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    patient_name: 'Sophia Chen',
    scheduled_at: getRelativeDateISO(7, 13, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-sophia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(0, 13, 0)
  },
  {
    id: 'apt-19',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    patient_name: 'David Miller',
    scheduled_at: getRelativeDateISO(-47, 9, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-david',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-54, 9, 0)
  },
  {
    id: 'apt-20',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    patient_name: 'Juan Perez',
    scheduled_at: getRelativeDateISO(-51, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-juan',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-58, 14, 0)
  },
  {
    id: 'apt-21',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    patient_name: 'Rachel Green',
    scheduled_at: getRelativeDateISO(-43, 14, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-rachel',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-50, 14, 0)
  },
  {
    id: 'apt-22',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    patient_name: 'Arthur Pendelton',
    scheduled_at: getRelativeDateISO(-49, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-arthur',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-56, 10, 0)
  },
  {
    id: 'apt-23',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    patient_name: 'Maria Garcia',
    scheduled_at: getRelativeDateISO(1, 15, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-maria',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-6, 15, 0)
  },
  {
    id: 'apt-24',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    patient_name: 'James Smith',
    scheduled_at: getRelativeDateISO(-42, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-james',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-49, 13, 0)
  },
  {
    id: 'apt-25',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    patient_name: 'Linda Johnson',
    scheduled_at: getRelativeDateISO(10, 14, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-linda',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(3, 14, 0)
  },
  {
    id: 'apt-26',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    patient_name: 'Robert Williams',
    scheduled_at: getRelativeDateISO(-33, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-robert',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-40, 12, 0)
  },
  {
    id: 'apt-27',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    patient_name: 'Patricia Brown',
    scheduled_at: getRelativeDateISO(-18, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-patricia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-25, 12, 0)
  },
  {
    id: 'apt-28',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    patient_name: 'John Jones',
    scheduled_at: getRelativeDateISO(-32, 13, 0),
    duration_minutes: 50,
    status: 'cancelled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-john',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-39, 13, 0)
  },
  {
    id: 'apt-29',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    patient_name: 'Jennifer Davis',
    scheduled_at: getRelativeDateISO(-10, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-jennifer',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-17, 10, 0)
  },
  {
    id: 'apt-30',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    patient_name: 'Michael Miller',
    scheduled_at: getRelativeDateISO(-36, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-michael',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-43, 13, 0)
  },
  {
    id: 'apt-31',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    patient_name: 'Elena Rostova',
    scheduled_at: getRelativeDateISO(-51, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-elena',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-58, 16, 0)
  },
  {
    id: 'apt-32',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    patient_name: 'Marcus Vance',
    scheduled_at: getRelativeDateISO(6, 15, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-marcus',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-1, 15, 0)
  },
  {
    id: 'apt-33',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    patient_name: 'Sophia Chen',
    scheduled_at: getRelativeDateISO(-47, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-sophia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-54, 10, 0)
  },
  {
    id: 'apt-34',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    patient_name: 'David Miller',
    scheduled_at: getRelativeDateISO(-54, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-david',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-61, 10, 0)
  },
  {
    id: 'apt-35',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    patient_name: 'Juan Perez',
    scheduled_at: getRelativeDateISO(7, 14, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-juan',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(0, 14, 0)
  },
  {
    id: 'apt-36',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    patient_name: 'Rachel Green',
    scheduled_at: getRelativeDateISO(3, 14, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-rachel',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-4, 14, 0)
  },
  {
    id: 'apt-37',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    patient_name: 'Arthur Pendelton',
    scheduled_at: getRelativeDateISO(-31, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-arthur',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-38, 14, 0)
  },
  {
    id: 'apt-38',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    patient_name: 'Maria Garcia',
    scheduled_at: getRelativeDateISO(-14, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-maria',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-21, 11, 0)
  },
  {
    id: 'apt-39',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    patient_name: 'James Smith',
    scheduled_at: getRelativeDateISO(-31, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-james',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-38, 14, 0)
  },
  {
    id: 'apt-40',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    patient_name: 'Linda Johnson',
    scheduled_at: getRelativeDateISO(-39, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-linda',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-46, 14, 0)
  },
  {
    id: 'apt-41',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    patient_name: 'Robert Williams',
    scheduled_at: getRelativeDateISO(-43, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-robert',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-50, 16, 0)
  },
  {
    id: 'apt-42',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    patient_name: 'Patricia Brown',
    scheduled_at: getRelativeDateISO(-1, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-patricia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-8, 10, 0)
  },
  {
    id: 'apt-43',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    patient_name: 'John Jones',
    scheduled_at: getRelativeDateISO(-44, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-john',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-51, 11, 0)
  },
  {
    id: 'apt-44',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    patient_name: 'Jennifer Davis',
    scheduled_at: getRelativeDateISO(-41, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-jennifer',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-48, 16, 0)
  },
  {
    id: 'apt-45',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    patient_name: 'Michael Miller',
    scheduled_at: getRelativeDateISO(-18, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-michael',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-25, 13, 0)
  },
  {
    id: 'apt-46',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    patient_name: 'Elena Rostova',
    scheduled_at: getRelativeDateISO(-26, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-elena',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-33, 11, 0)
  },
  {
    id: 'apt-47',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    patient_name: 'Marcus Vance',
    scheduled_at: getRelativeDateISO(2, 10, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-marcus',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-5, 10, 0)
  },
  {
    id: 'apt-48',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    patient_name: 'Sophia Chen',
    scheduled_at: getRelativeDateISO(-48, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-sophia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-55, 10, 0)
  },
  {
    id: 'apt-49',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    patient_name: 'David Miller',
    scheduled_at: getRelativeDateISO(-9, 9, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-david',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-16, 9, 0)
  },
  {
    id: 'apt-50',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    patient_name: 'Juan Perez',
    scheduled_at: getRelativeDateISO(-19, 16, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-juan',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-26, 16, 0)
  },
  {
    id: 'apt-51',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    patient_name: 'Rachel Green',
    scheduled_at: getRelativeDateISO(-56, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-rachel',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-63, 13, 0)
  },
  {
    id: 'apt-52',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    patient_name: 'Arthur Pendelton',
    scheduled_at: getRelativeDateISO(-27, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-arthur',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-34, 12, 0)
  },
  {
    id: 'apt-53',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    patient_name: 'Maria Garcia',
    scheduled_at: getRelativeDateISO(0, 11, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-maria',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-7, 11, 0)
  },
  {
    id: 'apt-54',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    patient_name: 'James Smith',
    scheduled_at: getRelativeDateISO(-34, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-james',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-41, 10, 0)
  },
  {
    id: 'apt-55',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    patient_name: 'Linda Johnson',
    scheduled_at: getRelativeDateISO(-21, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-linda',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-28, 10, 0)
  },
  {
    id: 'apt-56',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    patient_name: 'Robert Williams',
    scheduled_at: getRelativeDateISO(-28, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-robert',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-35, 12, 0)
  },
  {
    id: 'apt-57',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    patient_name: 'Patricia Brown',
    scheduled_at: getRelativeDateISO(-36, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-patricia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-43, 16, 0)
  },
  {
    id: 'apt-58',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    patient_name: 'John Jones',
    scheduled_at: getRelativeDateISO(-20, 16, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-john',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-27, 16, 0)
  },
  {
    id: 'apt-59',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    patient_name: 'Jennifer Davis',
    scheduled_at: getRelativeDateISO(-7, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-jennifer',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-14, 12, 0)
  },
  {
    id: 'apt-60',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    patient_name: 'Michael Miller',
    scheduled_at: getRelativeDateISO(-40, 15, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-michael',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-47, 15, 0)
  },
  {
    id: 'apt-61',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    patient_name: 'Elena Rostova',
    scheduled_at: getRelativeDateISO(9, 13, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-elena',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(2, 13, 0)
  },
  {
    id: 'apt-62',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    patient_name: 'Marcus Vance',
    scheduled_at: getRelativeDateISO(-24, 15, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-marcus',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-31, 15, 0)
  },
  {
    id: 'apt-63',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    patient_name: 'Sophia Chen',
    scheduled_at: getRelativeDateISO(8, 14, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-sophia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(1, 14, 0)
  },
  {
    id: 'apt-64',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    patient_name: 'David Miller',
    scheduled_at: getRelativeDateISO(-28, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-david',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-35, 14, 0)
  },
  {
    id: 'apt-65',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    patient_name: 'Juan Perez',
    scheduled_at: getRelativeDateISO(-37, 15, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-juan',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-44, 15, 0)
  },
  {
    id: 'apt-66',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    patient_name: 'Rachel Green',
    scheduled_at: getRelativeDateISO(-1, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-rachel',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-8, 14, 0)
  },
  {
    id: 'apt-67',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    patient_name: 'Arthur Pendelton',
    scheduled_at: getRelativeDateISO(-41, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-arthur',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-48, 13, 0)
  },
  {
    id: 'apt-68',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    patient_name: 'Maria Garcia',
    scheduled_at: getRelativeDateISO(-17, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-maria',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-24, 11, 0)
  },
  {
    id: 'apt-69',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    patient_name: 'James Smith',
    scheduled_at: getRelativeDateISO(-47, 11, 0),
    duration_minutes: 50,
    status: 'cancelled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-james',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-54, 11, 0)
  },
  {
    id: 'apt-70',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    patient_name: 'Linda Johnson',
    scheduled_at: getRelativeDateISO(-10, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-linda',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-17, 16, 0)
  },
  {
    id: 'apt-71',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    patient_name: 'Robert Williams',
    scheduled_at: getRelativeDateISO(-38, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-robert',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-45, 16, 0)
  },
  {
    id: 'apt-72',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    patient_name: 'Patricia Brown',
    scheduled_at: getRelativeDateISO(-48, 9, 0),
    duration_minutes: 50,
    status: 'cancelled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-patricia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-55, 9, 0)
  },
  {
    id: 'apt-73',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    patient_name: 'John Jones',
    scheduled_at: getRelativeDateISO(-43, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-john',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-50, 12, 0)
  },
  {
    id: 'apt-74',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    patient_name: 'Jennifer Davis',
    scheduled_at: getRelativeDateISO(-38, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-jennifer',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-45, 11, 0)
  },
  {
    id: 'apt-75',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    patient_name: 'Michael Miller',
    scheduled_at: getRelativeDateISO(-36, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-michael',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-43, 11, 0)
  },
  {
    id: 'apt-76',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    patient_name: 'Elena Rostova',
    scheduled_at: getRelativeDateISO(-2, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-elena',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-9, 16, 0)
  },
  {
    id: 'apt-77',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    patient_name: 'Marcus Vance',
    scheduled_at: getRelativeDateISO(-14, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-marcus',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-21, 14, 0)
  },
  {
    id: 'apt-78',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    patient_name: 'Sophia Chen',
    scheduled_at: getRelativeDateISO(-21, 14, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-sophia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-28, 14, 0)
  },
  {
    id: 'apt-79',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    patient_name: 'David Miller',
    scheduled_at: getRelativeDateISO(-13, 9, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-david',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-20, 9, 0)
  },
  {
    id: 'apt-80',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    patient_name: 'Juan Perez',
    scheduled_at: getRelativeDateISO(-27, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-juan',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-34, 16, 0)
  },
  {
    id: 'apt-81',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    patient_name: 'Rachel Green',
    scheduled_at: getRelativeDateISO(-37, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-rachel',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-44, 12, 0)
  },
  {
    id: 'apt-82',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    patient_name: 'Arthur Pendelton',
    scheduled_at: getRelativeDateISO(-6, 16, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-arthur',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-13, 16, 0)
  },
  {
    id: 'apt-83',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    patient_name: 'Maria Garcia',
    scheduled_at: getRelativeDateISO(-7, 11, 0),
    duration_minutes: 50,
    status: 'cancelled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-maria',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-14, 11, 0)
  },
  {
    id: 'apt-84',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    patient_name: 'James Smith',
    scheduled_at: getRelativeDateISO(-40, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-james',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-47, 12, 0)
  },
  {
    id: 'apt-85',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    patient_name: 'Linda Johnson',
    scheduled_at: getRelativeDateISO(-36, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-linda',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-43, 10, 0)
  },
  {
    id: 'apt-86',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    patient_name: 'Robert Williams',
    scheduled_at: getRelativeDateISO(-36, 11, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-robert',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-43, 11, 0)
  },
  {
    id: 'apt-87',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    patient_name: 'Patricia Brown',
    scheduled_at: getRelativeDateISO(-56, 12, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-patricia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-63, 12, 0)
  },
  {
    id: 'apt-88',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    patient_name: 'John Jones',
    scheduled_at: getRelativeDateISO(11, 15, 0),
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-john',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(4, 15, 0)
  },
  {
    id: 'apt-89',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    patient_name: 'Jennifer Davis',
    scheduled_at: getRelativeDateISO(-33, 10, 0),
    duration_minutes: 50,
    status: 'no_show',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-jennifer',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-40, 10, 0)
  },
  {
    id: 'apt-90',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    patient_name: 'Michael Miller',
    scheduled_at: getRelativeDateISO(-30, 16, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-michael',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-37, 16, 0)
  },
  {
    id: 'apt-91',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    patient_name: 'Elena Rostova',
    scheduled_at: getRelativeDateISO(-28, 9, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-elena',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-35, 9, 0)
  },
  {
    id: 'apt-92',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    patient_name: 'Marcus Vance',
    scheduled_at: getRelativeDateISO(-27, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-marcus',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-34, 13, 0)
  },
  {
    id: 'apt-93',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    patient_name: 'Sophia Chen',
    scheduled_at: getRelativeDateISO(-20, 10, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-sophia',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-27, 10, 0)
  },
  {
    id: 'apt-94',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    patient_name: 'David Miller',
    scheduled_at: getRelativeDateISO(-18, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-david',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-25, 13, 0)
  },
  {
    id: 'apt-95',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    patient_name: 'Juan Perez',
    scheduled_at: getRelativeDateISO(-34, 13, 0),
    duration_minutes: 50,
    status: 'completed',
    session_type: 'Individual Therapy',
    notes: 'Routine session.',
    telehealth_url: 'https://meet.google.com/lum-health-juan',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-41, 13, 0)
  },
  {
    id: 'apt-101',
    patient_id: 'p-16',
    practitioner_id: 'prac-1',
    patient_name: 'Incomplete Patient',
    scheduled_at: getRelativeDateISO(10, 10, 0), // 10 days in the future
    duration_minutes: 50,
    status: 'scheduled',
    session_type: 'Individual Therapy',
    notes: 'Initial intake session.',
    telehealth_url: 'https://meet.google.com/lum-health-incomplete',
    telehealth_provider: 'meet',
    created_at: getRelativeDateISO(-1, 10, 0)
  }
];

export const MOCK_CLINICAL_NOTES: ClinicalNote[] = [
  {
    id: 'note-1',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-20, 15, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Generalized Anxiety Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-20, 16, 0),
    updated_at: getRelativeDateISO(-20, 16, 0)
  },
  {
    id: 'note-2',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-32, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Major Depressive Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-32, 13, 0),
    updated_at: getRelativeDateISO(-32, 13, 0)
  },
  {
    id: 'note-3',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-6, 9, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-6, 10, 0),
    updated_at: getRelativeDateISO(-6, 10, 0)
  },
  {
    id: 'note-4',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-12, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-12, 15, 0),
    updated_at: getRelativeDateISO(-12, 15, 0)
  },
  {
    id: 'note-5',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-4, 15, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Agoraphobia'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-4, 16, 0),
    updated_at: getRelativeDateISO(-4, 16, 0)
  },
  {
    id: 'note-6',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-1, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-1, 12, 0),
    updated_at: getRelativeDateISO(-1, 12, 0)
  },
  {
    id: 'note-7',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-47, 9, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['MDD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-47, 10, 0),
    updated_at: getRelativeDateISO(-47, 10, 0)
  },
  {
    id: 'note-8',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-22, 9, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-22, 10, 0),
    updated_at: getRelativeDateISO(-22, 10, 0)
  },
  {
    id: 'note-9',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-48, 15, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['OCD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-48, 16, 0),
    updated_at: getRelativeDateISO(-48, 16, 0)
  },
  {
    id: 'note-10',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-21, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Major Depressive Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-21, 11, 0),
    updated_at: getRelativeDateISO(-21, 11, 0)
  },
  {
    id: 'note-11',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-47, 9, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-47, 10, 0),
    updated_at: getRelativeDateISO(-47, 10, 0)
  },
  {
    id: 'note-12',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-51, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Panic Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-51, 15, 0),
    updated_at: getRelativeDateISO(-51, 15, 0)
  },
  {
    id: 'note-13',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-49, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['GAD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-49, 11, 0),
    updated_at: getRelativeDateISO(-49, 11, 0)
  },
  {
    id: 'note-14',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-42, 13, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-42, 14, 0),
    updated_at: getRelativeDateISO(-42, 14, 0)
  },
  {
    id: 'note-15',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-33, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-33, 13, 0),
    updated_at: getRelativeDateISO(-33, 13, 0)
  },
  {
    id: 'note-16',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-18, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['OCD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-18, 13, 0),
    updated_at: getRelativeDateISO(-18, 13, 0)
  },
  {
    id: 'note-17',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-10, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['GAD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-10, 11, 0),
    updated_at: getRelativeDateISO(-10, 11, 0)
  },
  {
    id: 'note-18',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-36, 13, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Adjustment Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-36, 14, 0),
    updated_at: getRelativeDateISO(-36, 14, 0)
  },
  {
    id: 'note-19',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-47, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-47, 11, 0),
    updated_at: getRelativeDateISO(-47, 11, 0)
  },
  {
    id: 'note-20',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-54, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-54, 11, 0),
    updated_at: getRelativeDateISO(-54, 11, 0)
  },
  {
    id: 'note-21',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-14, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Bipolar II'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-14, 12, 0),
    updated_at: getRelativeDateISO(-14, 12, 0)
  },
  {
    id: 'note-22',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-31, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-31, 15, 0),
    updated_at: getRelativeDateISO(-31, 15, 0)
  },
  {
    id: 'note-23',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-39, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['MDD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-39, 15, 0),
    updated_at: getRelativeDateISO(-39, 15, 0)
  },
  {
    id: 'note-24',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-43, 16, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-43, 17, 0),
    updated_at: getRelativeDateISO(-43, 17, 0)
  },
  {
    id: 'note-25',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-1, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['OCD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-1, 11, 0),
    updated_at: getRelativeDateISO(-1, 11, 0)
  },
  {
    id: 'note-26',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-44, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Panic Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-44, 12, 0),
    updated_at: getRelativeDateISO(-44, 12, 0)
  },
  {
    id: 'note-27',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-18, 13, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Adjustment Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-18, 14, 0),
    updated_at: getRelativeDateISO(-18, 14, 0)
  },
  {
    id: 'note-28',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-26, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Generalized Anxiety Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-26, 12, 0),
    updated_at: getRelativeDateISO(-26, 12, 0)
  },
  {
    id: 'note-29',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-48, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-48, 11, 0),
    updated_at: getRelativeDateISO(-48, 11, 0)
  },
  {
    id: 'note-30',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-27, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['GAD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-27, 13, 0),
    updated_at: getRelativeDateISO(-27, 13, 0)
  },
  {
    id: 'note-31',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-34, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-34, 11, 0),
    updated_at: getRelativeDateISO(-34, 11, 0)
  },
  {
    id: 'note-32',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-21, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['MDD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-21, 11, 0),
    updated_at: getRelativeDateISO(-21, 11, 0)
  },
  {
    id: 'note-33',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-28, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-28, 13, 0),
    updated_at: getRelativeDateISO(-28, 13, 0)
  },
  {
    id: 'note-34',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-36, 16, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['OCD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-36, 17, 0),
    updated_at: getRelativeDateISO(-36, 17, 0)
  },
  {
    id: 'note-35',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-7, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['GAD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-7, 13, 0),
    updated_at: getRelativeDateISO(-7, 13, 0)
  },
  {
    id: 'note-36',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-40, 15, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Adjustment Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-40, 16, 0),
    updated_at: getRelativeDateISO(-40, 16, 0)
  },
  {
    id: 'note-37',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-24, 15, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Major Depressive Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-24, 16, 0),
    updated_at: getRelativeDateISO(-24, 16, 0)
  },
  {
    id: 'note-38',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-28, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-28, 15, 0),
    updated_at: getRelativeDateISO(-28, 15, 0)
  },
  {
    id: 'note-39',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-37, 15, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Panic Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-37, 16, 0),
    updated_at: getRelativeDateISO(-37, 16, 0)
  },
  {
    id: 'note-40',
    patient_id: 'p-6',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-1, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Agoraphobia'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-1, 15, 0),
    updated_at: getRelativeDateISO(-1, 15, 0)
  },
  {
    id: 'note-41',
    patient_id: 'p-7',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-41, 13, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['GAD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-41, 14, 0),
    updated_at: getRelativeDateISO(-41, 14, 0)
  },
  {
    id: 'note-42',
    patient_id: 'p-8',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-17, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Bipolar II'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-17, 12, 0),
    updated_at: getRelativeDateISO(-17, 12, 0)
  },
  {
    id: 'note-43',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-10, 16, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['MDD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-10, 17, 0),
    updated_at: getRelativeDateISO(-10, 17, 0)
  },
  {
    id: 'note-44',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-38, 16, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-38, 17, 0),
    updated_at: getRelativeDateISO(-38, 17, 0)
  },
  {
    id: 'note-45',
    patient_id: 'p-13',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-43, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Panic Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-43, 13, 0),
    updated_at: getRelativeDateISO(-43, 13, 0)
  },
  {
    id: 'note-46',
    patient_id: 'p-14',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-38, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['GAD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-38, 12, 0),
    updated_at: getRelativeDateISO(-38, 12, 0)
  },
  {
    id: 'note-47',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-36, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Adjustment Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-36, 12, 0),
    updated_at: getRelativeDateISO(-36, 12, 0)
  },
  {
    id: 'note-48',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-2, 16, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Generalized Anxiety Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-2, 17, 0),
    updated_at: getRelativeDateISO(-2, 17, 0)
  },
  {
    id: 'note-49',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-14, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Major Depressive Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-14, 15, 0),
    updated_at: getRelativeDateISO(-14, 15, 0)
  },
  {
    id: 'note-50',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-21, 14, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-21, 15, 0),
    updated_at: getRelativeDateISO(-21, 15, 0)
  },
  {
    id: 'note-51',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-27, 16, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Panic Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-27, 17, 0),
    updated_at: getRelativeDateISO(-27, 17, 0)
  },
  {
    id: 'note-52',
    patient_id: 'p-9',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-40, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-40, 13, 0),
    updated_at: getRelativeDateISO(-40, 13, 0)
  },
  {
    id: 'note-53',
    patient_id: 'p-10',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-36, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['MDD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-36, 11, 0),
    updated_at: getRelativeDateISO(-36, 11, 0)
  },
  {
    id: 'note-54',
    patient_id: 'p-11',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-36, 11, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-36, 12, 0),
    updated_at: getRelativeDateISO(-36, 12, 0)
  },
  {
    id: 'note-55',
    patient_id: 'p-12',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-56, 12, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['OCD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-56, 13, 0),
    updated_at: getRelativeDateISO(-56, 13, 0)
  },
  {
    id: 'note-56',
    patient_id: 'p-15',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-30, 16, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Adjustment Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-30, 17, 0),
    updated_at: getRelativeDateISO(-30, 17, 0)
  },
  {
    id: 'note-57',
    patient_id: 'p-1',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-28, 9, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Generalized Anxiety Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-28, 10, 0),
    updated_at: getRelativeDateISO(-28, 10, 0)
  },
  {
    id: 'note-58',
    patient_id: 'p-2',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-27, 13, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Major Depressive Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-27, 14, 0),
    updated_at: getRelativeDateISO(-27, 14, 0)
  },
  {
    id: 'note-59',
    patient_id: 'p-3',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-20, 10, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Social Anxiety'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-20, 11, 0),
    updated_at: getRelativeDateISO(-20, 11, 0)
  },
  {
    id: 'note-60',
    patient_id: 'p-4',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-18, 13, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['PTSD'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-18, 14, 0),
    updated_at: getRelativeDateISO(-18, 14, 0)
  },
  {
    id: 'note-61',
    patient_id: 'p-5',
    practitioner_id: 'prac-1',
    session_date: getRelativeDateISO(-34, 13, 0),
    discoveries: ['Patient discussed ongoing symptoms', 'Explored new coping mechanisms'],
    daily_actions: ['Practice mindfulness 10 mins daily', 'Journal triggers'],
    ailments: ['Panic Disorder'],
    raw_notes: 'Session progressed well. Addressed primary concerns and assigned homework.',
    created_at: getRelativeDateISO(-34, 14, 0),
    updated_at: getRelativeDateISO(-34, 14, 0)
  },
];

export function getDashboardStatsData(): PractitionerDashboardStats {
  const today = new Date();
  const todayAppointments = MOCK_APPOINTMENTS.filter((a) => {
    const aptDate = new Date(a.scheduled_at);
    return isSameDay(aptDate, today);
  });

  return {
    activePatientsCount: MOCK_PATIENTS.filter((p) => p.status === 'active').length,
    upcomingAppointmentsCount: todayAppointments.length,
    notesWrittenThisWeek: 18,
    recentAppointments: todayAppointments,
    recentNotes: MOCK_CLINICAL_NOTES.filter((p) => p.practitioner_id === 'prac-1').map(note => {
      const p = MOCK_PATIENTS.find(pat => pat.id === note.patient_id);
      return { ...note, patient_name: p ? `${p.first_name} ${p.last_name}` : 'Unknown Patient' };
    })
  };
}
